{{- if .Values.keyVault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: "85fa0df0-28e1-48e1-8194-28318de5f0cf"
  labels:
    app: mongodb
    service: mongodb
{{- end }}
