apiVersion: v2
name: cluster-autoscaler
description: Cluster Autoscaler for AKS - GitOps Managed
type: application
version: 1.0.0
appVersion: "1.30.0"

dependencies:
  - name: cluster-autoscaler
    version: "9.37.0"
    repository: "https://kubernetes.github.io/autoscaler"
