apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: robot-shop-allow-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app: robot-shop
    component: networking
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
  - to: []
    ports:
    - protocol: UDP
      port: 53
