apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "robot-shop.fullname" . }}-allow-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "robot-shop.labels" . | nindent 4 }}
    component: networking
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
  - to: []
    ports:
    - protocol: UDP
      port: 53
