{{- if .Values.global.ingress.tls }}
{{- range .Values.global.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
---
{{- end }}
{{- end }}
