{{- if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "robot-shop.fullname" . }}-allow-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "robot-shop.labels" . | nindent 4 }}
    component: security
spec:
  podSelector: {}  # Apply to all pods in namespace
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    # Allow ingress controller access
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    
    # Allow inter-service communication
    - from:
        - podSelector: {}  # Allow from all pods in namespace
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 3306  # MySQL
        - protocol: TCP
          port: 27017 # MongoDB
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 5672  # RabbitMQ
    
    # Allow monitoring
    {{- if .Values.global.monitoring.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090
    {{- end }}
  
  egress:
    # DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # HTTPS for external APIs
    - to: []
      ports:
        - protocol: TCP
          port: 443
    
    # Inter-service communication
    - to:
        - podSelector: {}  # Allow communication between all pods

---
# Default deny all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "robot-shop.fullname" . }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "robot-shop.labels" . | nindent 4 }}
    component: security
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
