apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    service: web
