apiVersion: v1
kind: ConfigMap
metadata:
  name: business-metrics-alert-rules
  namespace: monitoring
data:
  business-metrics-alerts.yaml: |
    groups:
      - name: business_metrics
        interval: 1m
        rules:
          # E-commerce Business Metrics
          
          - alert: LowOrderRate
            expr: rate(orders_total[5m]) < 0.1
            for: 10m
            labels:
              severity: warning
              type: business
            annotations:
              summary: "Order rate dropped significantly"
              description: "Only {{`{{ $value`}} }} orders per second (expected > 0.1)"
              impact: "Revenue impact - investigate checkout issues"
          
          - alert: HighCartAbandonmentRate
            expr: |
              (rate(cart_additions_total[5m]) - rate(orders_total[5m])) 
              / rate(cart_additions_total[5m]) > 0.8
            for: 10m
            labels:
              severity: warning
              type: business
            annotations:
              summary: "High cart abandonment rate"
              description: "{{`{{ $value`}} | humanizePercentage }} of carts abandoned"
              impact: "Revenue loss - check payment/shipping issues"
          
          - alert: PaymentFailureRateHigh
            expr: |
              rate(payment_failures_total[5m]) 
              / rate(payment_attempts_total[5m]) > 0.05
            for: 5m
            labels:
              severity: critical
              type: business
            annotations:
              summary: "High payment failure rate"
              description: "{{`{{ $value`}} | humanizePercentage }} of payments failing"
              impact: "Direct revenue loss - investigate payment gateway"
          
          - alert: LowUserRegistrations
            expr: rate(user_registrations_total[1h]) < 1
            for: 1h
            labels:
              severity: warning
              type: business
            annotations:
              summary: "User registration rate dropped"
              description: "Only {{`{{ $value`}} }} registrations per hour"
              impact: "Growth impact - check registration flow"
          
          - alert: HighProductViewToCartRatio
            expr: |
              rate(product_views_total[5m]) 
              / rate(cart_additions_total[5m]) > 100
            for: 15m
            labels:
              severity: warning
              type: business
            annotations:
              summary: "Low conversion from views to cart"
              description: "{{`{{ $value`}} }} views per cart addition"
              impact: "Conversion issue - check product pages"
          
          - alert: ShippingDelayIncreasing
            expr: |
              histogram_quantile(0.95, 
                rate(shipping_duration_seconds_bucket[1h])
              ) > 86400
            for: 1h
            labels:
              severity: warning
              type: business
            annotations:
              summary: "Shipping delays increasing"
              description: "P95 shipping time is {{`{{ $value`}} | humanizeDuration }}"
              impact: "Customer satisfaction - check shipping service"
          
          - alert: HighProductRatingDrop
            expr: |
              avg_over_time(product_rating_average[1h]) < 3.5
            for: 1h
            labels:
              severity: warning
              type: business
            annotations:
              summary: "Product ratings dropping"
              description: "Average rating is {{`{{ $value`}} }}"
              impact: "Quality issue - review recent products"
          
          - alert: InventoryLow
            expr: product_inventory_count < 10
            for: 5m
            labels:
              severity: warning
              type: business
            annotations:
              summary: "Low inventory for {{`{{ $labels`}}.product }}"
              description: "Only {{`{{ $value`}} }} items remaining"
              impact: "Potential stockout - reorder needed"
          
          - alert: RevenueDropSignificant
            expr: |
              rate(order_revenue_total[1h]) 
              < rate(order_revenue_total[1h] offset 24h) * 0.7
            for: 1h
            labels:
              severity: critical
              type: business
            annotations:
              summary: "Revenue dropped 30% vs yesterday"
              description: "Current: ${{`{{ $value`}} }}/hour"
              impact: "Major revenue impact - immediate investigation"
          
          - alert: HighRefundRate
            expr: |
              rate(refunds_total[1h]) 
              / rate(orders_total[1h]) > 0.1
            for: 1h
            labels:
              severity: warning
              type: business
            annotations:
              summary: "High refund rate"
              description: "{{`{{ $value`}} | humanizePercentage }} of orders refunded"
              impact: "Quality/satisfaction issue"
      
      - name: user_experience
        interval: 1m
        rules:
          - alert: SlowPageLoadTime
            expr: |
              histogram_quantile(0.95, 
                rate(page_load_duration_seconds_bucket[5m])
              ) > 3
            for: 10m
            labels:
              severity: warning
              type: user_experience
            annotations:
              summary: "Slow page load times"
              description: "P95 page load is {{`{{ $value`}} }}s (target: < 3s)"
              impact: "User experience degraded - check frontend performance"
          
          - alert: HighSearchFailureRate
            expr: |
              rate(search_no_results_total[5m]) 
              / rate(search_queries_total[5m]) > 0.3
            for: 10m
            labels:
              severity: warning
              type: user_experience
            annotations:
              summary: "High search failure rate"
              description: "{{`{{ $value`}} | humanizePercentage }} of searches return no results"
              impact: "User frustration - check search index"
          
          - alert: HighBounceRate
            expr: |
              rate(session_bounces_total[5m]) 
              / rate(sessions_total[5m]) > 0.6
            for: 15m
            labels:
              severity: warning
              type: user_experience
            annotations:
              summary: "High bounce rate"
              description: "{{`{{ $value`}} | humanizePercentage }} of users leaving immediately"
              impact: "Engagement issue - check landing pages"
