{{- if .Values.kube-prometheus-stack.grafana.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityClientID: {{ .Values.global.managedIdentity.clientId | quote }}
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectAlias: admin-password
        - |
          objectName: grafana-admin-user
          objectType: secret
          objectAlias: admin-user
  secretObjects:
    - secretName: grafana-admin-secret
      type: Opaque
      data:
        - objectName: admin-password
          key: admin-password
        - objectName: admin-user
          key: admin-user
{{- end }}
