apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-staging
  namespace: argocd
  labels:
    environment: staging
    app: monitoring
    tier: pre-production
spec:
  project: default
  source:
    repoURL: https://github.com/abdihakim-said/robot-shop-azure-platform
    targetRevision: HEAD  # Deploy from release branches
    path: helm-charts/monitoring
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: staging
        - name: prometheus.retention
          value: 30d  # Longer retention for staging
        - name: grafana.persistence.enabled
          value: "true"
        - name: alertmanager.config.global.slack_api_url
          value: "{{ .Values.slack.webhook_url }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Manual healing for staging validation
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  # Health checks for monitoring stack
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
