# Service Level Objectives (SLOs) for Robot Shop

apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-definitions
  namespace: monitoring
data:
  slos.yaml: |
    # Web Service SLOs
    web:
      availability:
        target: 99.9%  # 43 minutes downtime/month
        measurement: up{job="web"} == 1
        window: 30d
      
      latency:
        target: 95%    # 95% of requests < 500ms
        threshold: 500ms
        measurement: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="web"}[5m]))
        window: 7d
      
      error_rate:
        target: 99%    # < 1% error rate
        measurement: rate(http_requests_total{job="web",status=~"5.."}[5m]) / rate(http_requests_total{job="web"}[5m])
        window: 7d
    
    # Cart Service SLOs
    cart:
      availability:
        target: 99.5%
        measurement: up{job="cart"} == 1
        window: 30d
      
      latency:
        target: 95%
        threshold: 300ms
        measurement: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="cart"}[5m]))
        window: 7d
    
    # Database SLOs
    mysql:
      availability:
        target: 99.9%
        measurement: up{job="mysql"} == 1
        window: 30d
      
      connection_pool:
        target: 80%    # < 80% utilization
        measurement: mysql_global_status_threads_connected / mysql_global_variables_max_connections
        window: 7d
    
    # Overall Platform SLO
    platform:
      availability:
        target: 99.5%  # At least 8/12 services up
        measurement: count(up{namespace="robot-shop"} == 1) >= 8
        window: 30d
