apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robot-shop-web
  namespace: monitoring  # Must be in monitoring namespace
  labels:
    app: robot-shop
    service: web
spec:
  selector:
    matchLabels:
      service: web
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - robot-shop
