apiVersion: v1
kind: Service
metadata:
  name: web-metrics
  namespace: robot-shop
  labels:
    service: web
    app: robot-shop
spec:
  selector:
    service: web
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics  # NEW: Metrics port
    port: 9113
    targetPort: 9113
    protocol: TCP
  type: ClusterIP
