apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    # Azure Key Vault integration
    secrets-store.csi.x-k8s.io/used: "true"
type: Opaque
data:
  # These will be populated by Azure Key Vault CSI driver
  root-password: {{ .Values.auth.rootPassword | b64enc }}
  user-password: {{ .Values.auth.userPassword | b64enc }}
