apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    service: mysql
  annotations:
    azure.workload.identity/client-id: "4646deba-311f-4139-b108-41f780fda1f7"
