apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    service: mysql
  annotations:
    azure.workload.identity/client-id: "{{ .Values.global.azure.managedIdentityClientId | default "" }}"
