apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    service: mysql
  annotations:
    azure.workload.identity/client-id: "c31c60c4-9ea1-4723-a61e-c203019f357a"
