name: Deploy Service
description: Enterprise GitOps deployment for a single service

inputs:
  service-name:
    description: Name of the service to deploy
    required: true
  image-tag:
    description: Image tag to deploy
    required: true
  environment:
    description: Target environment (dev/staging/production)
    required: true
  github-token:
    description: GitHub token for API access
    required: true

runs:
  using: composite
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        echo "🔍 Validating deployment inputs..."
        echo "Service: ${{ inputs.service-name }}"
        echo "Image Tag: ${{ inputs.image-tag }}"
        echo "Environment: ${{ inputs.environment }}"
        
        # Validate environment
        case "${{ inputs.environment }}" in
          "dev"|"staging"|"production")
            echo "✅ Valid environment"
            ;;
          *)
            echo "❌ Invalid environment: ${{ inputs.environment }}"
            exit 1
            ;;
        esac
    
    - name: Update ArgoCD Application
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "🚀 Updating ArgoCD application for ${{ inputs.service-name }}"
        echo "This would update the GitOps repository with new image tag"
        echo "Image: robotshopacr.azurecr.io/${{ inputs.service-name }}:${{ inputs.image-tag }}"
