name: CD - Deploy to Development

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  AZURE_RESOURCE_GROUP: robot-shop-dev-rg
  AKS_CLUSTER_NAME: robot-shop-dev-aks
  NAMESPACE: robot-shop

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://${{ steps.get-url.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.13.0'

      - name: Deploy Application
        run: |
          helm upgrade --install robot-shop ./helm \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --values ./helm/values-${{ env.ENVIRONMENT }}.yaml \
            --wait \
            --timeout 10m \
            --atomic

      - name: Verify Deployment
        run: |
          echo "Checking pod status..."
          kubectl get pods -n ${{ env.NAMESPACE }}
          
          echo "Waiting for all pods to be ready..."
          kubectl wait --for=condition=ready pod --all -n ${{ env.NAMESPACE }} --timeout=300s
          
          echo "✅ All pods are running"

      - name: Get Application URL
        id: get-url
        run: |
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "url=${URL}:8080" >> $GITHUB_OUTPUT
          echo "🌐 Application URL: http://${URL}:8080"

      - name: Smoke Test
        run: |
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$URL" ]; then
            echo "Running smoke test..."
            curl -f http://${URL}:8080 || exit 1
            echo "✅ Smoke test passed"
          fi
