name: CD - Deploy to Production

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  ENVIRONMENT: prod
  AZURE_RESOURCE_GROUP: robot-shop-prod-rg
  AKS_CLUSTER_NAME: robot-shop-prod-aks
  NAMESPACE: robot-shop

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://${{ steps.get-url.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.13.0'

      - name: Backup Current Release
        run: |
          echo "Creating backup of current release..."
          helm get values robot-shop -n ${{ env.NAMESPACE }} > backup-values.yaml || true
          echo "✅ Backup created"

      - name: Deploy Application
        run: |
          helm upgrade --install robot-shop ./helm \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --values ./helm/values-${{ env.ENVIRONMENT }}.yaml \
            --wait \
            --timeout 15m \
            --atomic

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }}
          kubectl wait --for=condition=ready pod --all -n ${{ env.NAMESPACE }} --timeout=600s

      - name: Check HPA Status
        run: |
          echo "Checking autoscaling configuration..."
          kubectl get hpa -n ${{ env.NAMESPACE }}

      - name: Get Application URL
        id: get-url
        run: |
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "url=${URL}:8080" >> $GITHUB_OUTPUT
          echo "🌐 Production URL: http://${URL}:8080"

      - name: Production Smoke Tests
        run: |
          echo "Running production smoke tests..."
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$URL" ]; then
            for i in {1..5}; do
              curl -f http://${URL}:8080 && break || sleep 10
            done
            echo "✅ Production smoke tests passed"
          fi

      - name: Notify Success
        if: success()
        run: |
          echo "🎉 Production deployment successful!"
          echo "Version: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"
