name: CD - Deploy to Staging

on:
  workflow_run:
    workflows: ["CD - Deploy to Development"]
    types: [completed]
    branches: [develop]
  workflow_dispatch:

env:
  ENVIRONMENT: staging
  AZURE_RESOURCE_GROUP: robot-shop-staging-rg
  AKS_CLUSTER_NAME: robot-shop-staging-aks
  NAMESPACE: robot-shop

jobs:
  promote-to-staging:
    name: Promote to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment:
      name: staging
      url: http://${{ steps.get-url.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.13.0'

      - name: Deploy Application
        run: |
          helm upgrade --install robot-shop ./helm \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --values ./helm/values-${{ env.ENVIRONMENT }}.yaml \
            --wait \
            --timeout 10m \
            --atomic

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }}
          kubectl wait --for=condition=ready pod --all -n ${{ env.NAMESPACE }} --timeout=300s

      - name: Check HPA
        run: |
          echo "Checking Horizontal Pod Autoscalers..."
          kubectl get hpa -n ${{ env.NAMESPACE }}

      - name: Get Application URL
        id: get-url
        run: |
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "url=${URL}:8080" >> $GITHUB_OUTPUT

      - name: Integration Tests
        run: |
          echo "Running integration tests..."
          URL=$(kubectl get svc web -n ${{ env.NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$URL" ]; then
            curl -f http://${URL}:8080 || exit 1
            echo "✅ Integration tests passed"
          fi
