apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment
    service: payment
  annotations:
    azure.workload.identity/client-id: 85fa0df0-28e1-48e1-8194-28318de5f0cf
