apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop-dev
  namespace: argocd
  labels:
    environment: dev
    app: robot-shop
spec:
  project: default
  
  source:
    repoURL: https://github.com/abdihakim-said/robot-shop-azure-platform
    targetRevision: develop  # Auto-deploy from develop branch
    path: helm-charts/robot-shop
    helm:
      valueFiles:
        - values-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: robot-shop
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
