#!/bin/bash

echo "🎯 Robot Shop - Interview Demo Script"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Get web IP
WEB_IP=$(kubectl get svc web -n robot-shop -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

echo "📊 WHAT'S DEPLOYED:"
echo "─────────────────────────────────────────────────────────"
echo "✅ 12 microservices running"
echo "✅ 0 CRITICAL vulnerabilities"
echo "✅ Prometheus + Grafana monitoring"
echo "✅ 35 alert rules active"
echo "✅ AlertManager configured"
echo ""

echo "🌐 LIVE APPLICATION:"
echo "─────────────────────────────────────────────────────────"
echo "URL: http://$WEB_IP:8080"
echo ""
echo "Services:"
kubectl get pods -n robot-shop -o custom-columns=NAME:.metadata.name,STATUS:.status.phase,RESTARTS:.status.containerStatuses[0].restartCount
echo ""

echo "🔍 MONITORING ACCESS:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "1. GRAFANA (Dashboards)"
echo "   kubectl port-forward -n monitoring svc/monitoring-grafana 3000:80"
echo "   URL: http://localhost:3000"
echo "   Login: admin / ChangeMe123!"
echo ""
echo "2. PROMETHEUS (Metrics & Alerts)"
echo "   kubectl port-forward -n monitoring svc/monitoring-kube-prometheus-prometheus 9090:9090"
echo "   URL: http://localhost:9090"
echo ""
echo "3. ALERTMANAGER (Alert Routing)"
echo "   kubectl port-forward -n monitoring svc/alertmanager-monitoring-kube-prometheus-alertmanager 9093:9093"
echo "   URL: http://localhost:9093"
echo ""

echo "🧪 DEMO SCENARIOS:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Demo 1: Show Live Application"
echo "  open http://$WEB_IP:8080"
echo "  - Browse products"
echo "  - Add to cart"
echo "  - Show 12 services working together"
echo ""
echo "Demo 2: Show Monitoring"
echo "  kubectl port-forward -n monitoring svc/monitoring-grafana 3000:80 &"
echo "  open http://localhost:3000"
echo "  - Navigate to Dashboards"
echo "  - Show Kubernetes metrics"
echo "  - Show resource usage"
echo ""
echo "Demo 3: Show Prometheus Metrics"
echo "  kubectl port-forward -n monitoring svc/monitoring-kube-prometheus-prometheus 9090:9090 &"
echo "  open http://localhost:9090"
echo "  - Go to Status → Targets (show what's monitored)"
echo "  - Go to Alerts (show active alert rules)"
echo "  - Try query: kube_pod_status_phase{namespace=\"robot-shop\"}"
echo ""
echo "Demo 4: Trigger Alert (Self-Healing)"
echo "  kubectl delete pod -n robot-shop -l app=cart"
echo "  kubectl get pods -n robot-shop -l app=cart -w"
echo "  - Show pod terminates"
echo "  - Show Kubernetes creates new pod"
echo "  - Show pod becomes Ready (~30 seconds)"
echo "  - Explain: This would trigger PodDown alert in 2 minutes"
echo ""
echo "Demo 5: Show Resource Usage"
echo "  kubectl top pods -n robot-shop"
echo "  kubectl top nodes"
echo "  - Show CPU and memory usage"
echo "  - Explain resource limits"
echo ""
echo "Demo 6: Show Logs"
echo "  kubectl logs -n robot-shop deployment/web --tail=20"
echo "  - Show application logs"
echo "  - Explain log aggregation"
echo ""

echo "💼 KEY TALKING POINTS:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Security:"
echo "  - 89 CRITICAL CVEs → 0 CRITICAL"
echo "  - 3-layer security scanning (TruffleHog, Trivy, Semgrep)"
echo "  - Infrastructure security (tfsec, Checkov)"
echo ""
echo "Monitoring:"
echo "  - Prometheus + Grafana deployed"
echo "  - 35 alert rules active"
echo "  - SLOs defined (99.9% availability, P95 < 500ms)"
echo "  - Runbooks for incident response"
echo ""
echo "Infrastructure:"
echo "  - Infrastructure as Code (Terraform)"
echo "  - GitFlow automation"
echo "  - 3 environments (dev deployed, staging/prod ready)"
echo "  - Environment-specific security"
echo ""
echo "SRE Practices:"
echo "  - Self-healing (Kubernetes)"
echo "  - Error budgets"
echo "  - Incident management"
echo "  - Real incident experience"
echo ""

echo "📈 METRICS TO SHOW:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "In Prometheus, try these queries:"
echo ""
echo "1. Pod status:"
echo "   kube_pod_status_phase{namespace=\"robot-shop\"}"
echo ""
echo "2. CPU usage:"
echo "   rate(container_cpu_usage_seconds_total{namespace=\"robot-shop\"}[5m])"
echo ""
echo "3. Memory usage:"
echo "   container_memory_usage_bytes{namespace=\"robot-shop\"}"
echo ""
echo "4. Pod restarts:"
echo "   kube_pod_container_status_restarts_total{namespace=\"robot-shop\"}"
echo ""
echo "5. Network traffic:"
echo "   rate(container_network_receive_bytes_total{namespace=\"robot-shop\"}[5m])"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🚀 YOU'RE READY FOR INTERVIEWS!"
echo "═══════════════════════════════════════════════════════════"
