apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: "c31c60c4-9ea1-4723-a61e-c203019f357a"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
